development:
    adapter: sqlite3
    database: db/development.sqlite3

production:
    encoding: unicode
    adapter: postgresql
    username: <%= ENV['DATABASE_USERNAME'] %>
    port: 5432
    host: <%= ENV['DATABASE_HOST'] %>
    database: <%= ENV['DATABASE'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
